name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      id: step1
      run: exit 1
      continue-on-error: true

    - name: Step 2
    if: steps.step1.outcome == 'failure'
    run: echo "This step have is running because exit 1"